server:
  shutdown: GRACEFUL
  port: 8080
spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s


management:
  endpoint:
    shutdown:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - "*"
application:
  unloadDelay: 2m

